routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Route::get('/','FrontendController@index')->name('landing');

Auth::routes(['register' => false,'verify' => true]);

Route::get('/sign-up',function (){
   return view('home.signup');
})->name('user-register');

//checkout and view cart route
Route::get('/cart','ProductsController@showCart')->name('cart-detail');
Route::get('/checkout','ProductsController@checkOut')->name('checkout')->middleware('auth');

//review route define
Route::post('/review/{product_id}','ProductsController@submitReview')->name('post-review');
// cart ajax
Route::get('/cart/add','ProductsController@addToCart');
//email verification
Route::get('/activate/{user_id}/{token}','UsersController@activeUser')->name('user_active');

// resource route
Route::post('/sign-up','UsersController@submitUser')->name('post-user-register');


Route::get('/home', 'HomeController@index')->name('home');

//getHelpAndFaq route
Route::get('/help-and-faq','PageController@getHelpAndFaq')->name('help-and-faq');
//Route::get('/pages/{slug}','PageController@getPageDetail')->name('page-detail');


Route::get('/shop','ProductsController@getAllProducts')->name('all-product-list');

Route::get('/category/{slug}','CategoryController@getProductByPrentCat')->name('parent-category-product');
Route::get('/category/{slug}/{child_slug}','CategoryController@getProductByChildCat')->name('child-category-product');





Route::get('/products/{slug}','ProductsController@show')->name('products-show');

/*------------------------ Admin Route ---------------------------*/
Route::group(['prefix' => 'admin','middleware' => ['auth','admin']],function (){

    Route::get('/',function (){
        return view('admin.dashboard');
    })->name('admin');

    Route::resource('banner','BannerController')->except('show');
    Route::resource('category','CategoryController');
    Route::resource('products','ProductsController');
    Route::resource('users','UsersController');
    Route::resource('pages','PageController');
    Route::resource('order','OrderController');
    Route::post('/category/child','CategoryController@getChildCats')->name('get-child');


    Route::get('file-manager',function (){
        return view('admin.file-manager');
    })->name('file-manager');
});

/*------------------------ End Admin Route ---------------------------*/

/*------------------------ Vendor Route ---------------------------*/
Route::group(['prefix' => 'vendor','middleware' => ['auth','vendor']],function (){
    Route::get('/','HomeController@index')->name('vendor');
});
/*------------------------ End Vendor Route ---------------------------*/

/*------------------------ Customer Route ---------------------------*/
Route::group(['prefix' => 'customer','middleware' => ['auth','customer']],function (){
    Route::get('/',function (){
        return view('home');
    })->name('customer');
});

/*------------------------ End Customer Route ---------------------------*/
Route::group(['middleware' => 'auth'], function () {
    Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
    // list all lfm routes here...
});

resources/views/admin/sections/notification.blade.php
@if(session('success'))
<div class="alert alert-success alert-bordered">
    {{session('success')}}
</div>
@endif
@if(session('error'))
    <div class="alert alert-error alert-bordered">
        {{session('error')}}
    </div>
@endif

@if(session('status'))
    <div class="alert alert-success alert-bordered">
        {{session('status')}}
    </div>
@endif


@if(session('warning'))
    <div class="alert alert-warning alert-bordered">
        {{session('warning')}}
    </div>
@endif

resources/views/admin/sections/sidebar.blade.php
<!-- START SIDEBAR-->
<nav class="page-sidebar" id="sidebar">
    <div id="sidebar-collapse">
        <div class="admin-block d-flex">
            <div>
                <img src="{{ asset('images/userinfo.png') }}" width="45px" style="background: #ffffff;">
            </div>
            <div class="admin-info">
                <div class="font-strong">{{ request()->user()->name }}</div><small>Administrator</small></div>
        </div>
        <ul class="side-menu metismenu">
            <li>
                <a class="active" href="{{ route('admin') }}"><i class="sidebar-item-icon fa fa-th-large"></i>
                    <span class="nav-label">Dashboard</span>
                </a>
            </li>

            <li class="heading">FEATURES</li>

            <li>
                <a href="{{ route('banner.index') }}"><i class="sidebar-item-icon fa fa-image"></i>
                    <span class="nav-label">Banner Management</span>
                </a>
            </li>
            <li>
                <a href="{{ route('category.index') }}"><i class="sidebar-item-icon fa fa-sitemap"></i>
                    <span class="nav-label">Category Management</span>
                </a>
            </li>
            <li>
                <a href="{{ route('file-manager') }}"><i class="sidebar-item-icon fa fa-image"></i>
                    <span class="nav-label">Media Management</span>
                </a>
            </li>
            <li>
                <a href="{{ route('products.index') }}"><i class="sidebar-item-icon fa fa-shopping-basket"></i>
                    <span class="nav-label">Product Management</span>
                </a>
            </li>
            <li>
                <a href="{{ route('order.index') }}"><i class="sidebar-item-icon fa fa-shopping-bag"></i>
                    <span class="nav-label">Order Management</span>
                </a>
            </li>
            <li>
                <a href="{{ route('users.index') }}"><i class="sidebar-item-icon fa fa-users"></i>
                    <span class="nav-label">Users Management</span>
                </a>
            </li>
            <li>
                <a href="{{ route('pages.index') }}"><i class="sidebar-item-icon fa fa-paperclip"></i>
                    <span class="nav-label">Pages Management</span>
                </a>
            </li>
            <li>
                <a href="icons.html"><i class="sidebar-item-icon fa fa-comments"></i>
                    <span class="nav-label">Review Management</span>
                </a>
            </li>
        </ul>
    </div>
</nav>

<!-- END SIDEBAR-->

resources/views/admin/sections/top-nav.blade.php
<!-- START HEADER-->
<header class="header">
    <div class="page-brand">
        <a class="link" href="index.html">
                    <span class="brand">Admin&nbsp;
                        <span class="brand-tip">Bcom</span>
                    </span>
            <span class="brand-mini">AC</span>
        </a>
    </div>
    <div class="flexbox flex-1">
        <!-- START TOP-LEFT TOOLBAR-->
        <ul class="nav navbar-toolbar">
            <li>
                <a class="nav-link sidebar-toggler js-sidebar-toggler"><i class="ti-menu"></i></a>
            </li>

        </ul>
        <!-- END TOP-LEFT TOOLBAR-->
        <!-- START TOP-RIGHT TOOLBAR-->
        <ul class="nav navbar-toolbar">
            <li class="dropdown dropdown-notification">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell-o rel"><span class="notify-signal"></span></i></a>
                <ul class="dropdown-menu dropdown-menu-right dropdown-menu-media">
                    <li class="dropdown-menu-header">
                        <div>
                            <span><strong>5 New</strong> Notifications</span>
                            <a class="pull-right" href="javascript:;">view all</a>
                        </div>
                    </li>
                    <li class="list-group list-group-divider scroller" data-height="240px" data-color="#71808f">
                        <div>
                            <a class="list-group-item">
                                <div class="media">
                                    <div class="media-img">
                                        <span class="badge badge-success badge-big"><i class="fa fa-check"></i></span>
                                    </div>
                                    <div class="media-body">
                                        <div class="font-13">4 task compiled</div><small class="text-muted">22 mins</small></div>
                                </div>
                            </a>
                            <a class="list-group-item">
                                <div class="media">
                                    <div class="media-img">
                                        <span class="badge badge-default badge-big"><i class="fa fa-shopping-basket"></i></span>
                                    </div>
                                    <div class="media-body">
                                        <div class="font-13">You have 12 new orders</div><small class="text-muted">40 mins</small></div>
                                </div>
                            </a>
                            <a class="list-group-item">
                                <div class="media">
                                    <div class="media-img">
                                        <span class="badge badge-danger badge-big"><i class="fa fa-bolt"></i></span>
                                    </div>
                                    <div class="media-body">
                                        <div class="font-13">Server #7 rebooted</div><small class="text-muted">2 hrs</small></div>
                                </div>
                            </a>
                            <a class="list-group-item">
                                <div class="media">
                                    <div class="media-img">
                                        <span class="badge badge-success badge-big"><i class="fa fa-user"></i></span>
                                    </div>
                                    <div class="media-body">
                                        <div class="font-13">New user registered</div><small class="text-muted">2 hrs</small></div>
                                </div>
                            </a>
                        </div>
                    </li>
                </ul>
            </li>

            <li class="dropdown dropdown-user">
                <a class="nav-link dropdown-toggle link" data-toggle="dropdown">
                    <img src="{{ asset('images/userinfo.png') }}" />
                    <span></span>{{ request()->user()->name }}<i class="fa fa-angle-down m-l-5"></i>
                </a>

                <ul class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                             document.getElementById('logout-form').submit();">
                        <i class="fa fa-power-off"></i> Logout
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </ul>

            </li>
        </ul>
        <!-- END TOP-RIGHT TOOLBAR-->
    </div>
</header>
<!-- END HEADER-->