routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Route::get('/','FrontendController@index')->name('landing');

Auth::routes(['register' => false,'verify' => true]);

Route::get('/sign-up',function (){
   return view('home.signup');
})->name('user-register');

//checkout and view cart route
Route::get('/cart','ProductsController@showCart')->name('cart-detail');
Route::get('/checkout','ProductsController@checkOut')->name('checkout')->middleware('auth');

//review route define
Route::post('/review/{product_id}','ProductsController@submitReview')->name('post-review');
// cart ajax
Route::get('/cart/add','ProductsController@addToCart');
//email verification
Route::get('/activate/{user_id}/{token}','UsersController@activeUser')->name('user_active');

// resource route
Route::post('/sign-up','UsersController@submitUser')->name('post-user-register');


Route::get('/home', 'HomeController@index')->name('home');

//getHelpAndFaq route
Route::get('/help-and-faq','PageController@getHelpAndFaq')->name('help-and-faq');
//Route::get('/pages/{slug}','PageController@getPageDetail')->name('page-detail');


Route::get('/shop','ProductsController@getAllProducts')->name('all-product-list');

Route::get('/category/{slug}','CategoryController@getProductByPrentCat')->name('parent-category-product');
Route::get('/category/{slug}/{child_slug}','CategoryController@getProductByChildCat')->name('child-category-product');





Route::get('/products/{slug}','ProductsController@show')->name('products-show');

/*------------------------ Admin Route ---------------------------*/
Route::group(['prefix' => 'admin','middleware' => ['auth','admin']],function (){

    Route::get('/',function (){
        return view('admin.dashboard');
    })->name('admin');

    Route::resource('banner','BannerController')->except('show');
    Route::resource('category','CategoryController');
    Route::resource('products','ProductsController');
    Route::resource('users','UsersController');
    Route::resource('pages','PageController');
    Route::resource('order','OrderController');
    Route::post('/category/child','CategoryController@getChildCats')->name('get-child');


    Route::get('file-manager',function (){
        return view('admin.file-manager');
    })->name('file-manager');
});

/*------------------------ End Admin Route ---------------------------*/

/*------------------------ Vendor Route ---------------------------*/
Route::group(['prefix' => 'vendor','middleware' => ['auth','vendor']],function (){
    Route::get('/','HomeController@index')->name('vendor');
});
/*------------------------ End Vendor Route ---------------------------*/

/*------------------------ Customer Route ---------------------------*/
Route::group(['prefix' => 'customer','middleware' => ['auth','customer']],function (){
    Route::get('/',function (){
        return view('home');
    })->name('customer');
});

/*------------------------ End Customer Route ---------------------------*/
Route::group(['middleware' => 'auth'], function () {
    Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\Controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\Controllers\UploadController@upload');
    // list all lfm routes here...
});

resources/views/admin/banner-form.blade.php
@extends('admin.layouts.admin')
@section('content')
    <div class="page-content fade-in-up">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-head">
                        <div class="ibox-title">Banner {{ isset($banner_data) ? 'Update' : 'Add' }}</div>
                    </div>
                    <div class="ibox-body">
                        @if(isset($banner_data))
                                {{ Form::open(['url' => route('banner.update',$banner_data->id),'class' => 'form', 'id' => 'banner_add', 'files' => true,'method' => 'patch']) }}
                            @else
                                {{ Form::open(['url' => route('banner.store'),'class' => 'form', 'id' => 'banner_add', 'files' => true ]) }}

                            @endif
                                <div class="form-group row">
                                    {{ Form::label('title','Title: ',['class' => 'col-sm-3']) }}
                                    <div class="col-sm-9">
                                        {{ Form::text('title',@$banner_data->title ,['class' => 'form-control'.($errors->has('title') ? 'is-invalid': ''),'id' => 'title' ,'required' => true,'placeholder' => 'Enter Title']) }}
                                        {{--name,value,class--}}
                                        @error('title')
                                        <p class="invalid-feedback">
                                            {{ $message }}
                                        </p>
                                        @enderror
                                    </div>
                                </div>

                        <div class="form-group row">
                            {{ Form::label('link','Link: ',['class' => 'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::url('link',@$banner_data->link,['class' => 'form-control'.($errors->has('link') ? 'is-invalid': ''),'id' => 'link' ,'required' => true,'placeholder' => 'Enter Link']) }}
                                {{--name,value,class--}}
                                @error('title')
                                <p class="invalid-feedback">
                                    {{ $message }}
                                </p>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row">
                            {{ Form::label('status','Status: ',['class' => 'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::select('status',['active' => 'Active','inactive' => 'Inactive'],@$banner_data->status,['class' => 'form-control'.($errors->has('status') ? 'is-invalid': ''),'id' => 'status' ,'required' => true]) }}

                                @error('status')
                                <p class="invalid-feedback">
                                    {{ $message }}
                                </p>
                                @enderror
                            </div>
                        </div>



                        <div class="form-group row">
                            {{ Form::label('image','Image: ',['class' => 'col-sm-3']) }}
                            <div class="col-sm-4">
                                {{ Form::file('image',['class' => 'form-control-file'.($errors->has('image') ? 'is-invalid': ''),'id' => 'image' ,'required' => (isset($banner_data) ? false : true),'accept' => 'image/*']) }}
                                {{--name,value,class--}}
                                @error('image')
                                <p class="invalid-feedback">
                                    {{ $message }}
                                </p>
                                @enderror
                            </div>

                            <div class="col-sm-4">
                                @if(isset($banner_data) && $banner_data->image != null && file_exists(public_path().'/uploads/banner/Thumb-'.$banner_data->image))
                                    <img src="{{ asset('uploads/banner/Thumb-' .$banner_data->image) }}" alt="image" style="max-width: 150px;" class="img img-thumbnail img-fluid">
                                @endif
                            </div>
                        </div>


                        <div class="form-group row">
                            {{ Form::label('button','',['class' => 'col-sm-3']) }}
                            <div class="col-sm-9">
                                {{ Form::button('<i class="fa fa-trash"></i> Reset',['class' => 'btn btn-danger', 'type' => 'reset']) }}
                                {{ Form::button('<i class="fa fa-send"></i> Submit',['class' => 'btn btn-success', 'type' => 'submit']) }}
                            </div>
                        </div>

                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/banner.blade.php
@extends('admin.layouts.admin')
@section('content')
@section('styles')
    {{--        <link rel="stylesheet" href="{{ asset('assets/admin/css/datatable.min.css') }}">--}}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
@endsection
@section('content')
    <div class="page-content fade-in-up">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-head">
                        <div class="ibox-title">Banner List</div>
                        <div class="ibox-tools">
                            <a href="{{ route('banner.create') }}"><button class="btn btn-success"><i class="fa fa-plus"></i> Add Banner</button></a>
                        </div>
                    </div>
                    <div class="ibox-body">
                        <table class="table table-striped table-hover" id="table_id">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Thumbnail</th>
                                    <th>Link</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            @if($banner_list)
                                @foreach($banner_list as $key => $value)
                                        <tr>
                                            <td>{{ $key+1 }}</td>
                                            <td>
                                                @if($value->image != null && file_exists(public_path().'/uploads/banner/Thumb-'.$value->image))
                                                    <img src="{{ asset('uploads/banner/Thumb-'.$value->image) }}" alt="img" style="max-width: 150px" class="img img-responsive img-thumbnail">
                                                @endif
                                            </td>
                                            <td>
                                                <a href="{{ $value->link }}" target="_blank"> {{ $value->link }}</a>
                                            </td>
                                            <td>{{ ucfirst($value->status) }}</td>
                                            <td>
                                                <a href="{{ route('banner.edit',$value->id) }}" class="btn btn-success" style="border-radius: 50%">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                                {{--delelte data--}}
                                                {{ Form::open(['url' => route('banner.destroy',$value->id),'class' => 'form' ,'method' =>'delete','onsubmit' =>"return confirm('Are u sure u want to delete this banner.?')"]) }}
                                                {{Form::button('<i class="fa fa-trash"></i>',['class' => 'btn btn-danger','style' => 'border-radius:50% ','type' => 'submit'])}}
                                                {{ Form::close() }}
                                            </td>
                                        </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>



    </div>

@endsection
@section('scripts')
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    {{--    <script rel="stylesheet" href="{{ asset('assets/admin/js/datatable.min.js') }}"></script>--}}
    <script>
        $(document).ready( function () {
            $('#table_id').DataTable();
        } );
    </script>
@endsection

resources/views/admin/category.blade.php
@extends('admin.layouts.admin')
@section('content')
@section('styles')
    {{--        <link rel="stylesheet" href="{{ asset('assets/admin/css/datatable.min.css') }}">--}}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
@endsection
@section('content')
    <div class="page-content fade-in-up">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-head">
                        <div class="ibox-title">Category List</div>
                        <div class="ibox-tools">
                            <a href="{{ route('category.create') }}"><button class="btn btn-success"><i class="fa fa-plus"></i> Add Category</button></a>
                        </div>
                    </div>
                    <div class="ibox-body">
                        <table class="table table-striped table-hover" id="table_id">
                            <thead>
                            <tr>
                                <th>S.NO</th>
                                <th>Title</th>
                                <th>Thumbnail</th>
                                <th>slug</th>
                                <th>Is Parent</th>
                                <th>Parent</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if($category_list)
                                @foreach($category_list as $key => $value)
                                    <tr>
                                        <td>{{ $key+1 }}</td>
                                        <td>{{ $value->title }}</td>
                                        <td>
                                            @if($value->image != null && file_exists(public_path().'/uploads/category/Thumb-'.$value->image))
                                                <img src="{{ asset('uploads/category/Thumb-'.$value->image) }}" alt="img" style="max-width: 150px" class="img img-responsive img-thumbnail">
                                            @endif
                                        </td>
                                        <td>
                                            {{ $value->slug }}
                                        </td>
                                        <td>
                                            {{ $value->is_parent == 1 ? 'Yes' : 'No' }}
                                        </td>

                                        <td>{{ $value->parent_info['title'] }}</td>
                                        <td>{{ ucfirst($value->status) }}</td>
                                        <td>
                                            <a href="{{ route('category.edit',$value->id) }}" class="btn btn-success" style="border-radius: 50%">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            {{--delelte data--}}
                                            {{ Form::open(['url' => route('category.destroy',$value->id),'class' => 'form' ,'method' =>'delete','onsubmit' =>"return confirm('Are u sure u want to delete this category.?')"]) }}
                                            {{Form::button('<i class="fa fa-trash"></i>',['class' => 'btn btn-danger','style' => 'border-radius:50% ','type' => 'submit'])}}
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>



    </div>

@endsection
@section('scripts')
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    {{--    <script rel="stylesheet" href="{{ asset('assets/admin/js/datatable.min.js') }}"></script>--}}
    <script>
        $(document).ready( function () {
            $('#table_id').DataTable();
        } );
    </script>
@endsection

resources/views/admin/order-table.blade.php
@extends('admin.layouts.admin')
@section('content')
@section('styles')
    {{--        <link rel="stylesheet" href="{{ asset('assets/admin/css/datatable.min.css') }}">--}}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
@endsection
@section('content')
    <div class="page-content fade-in-up">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-head">
                        <div class="ibox-title">Order List</div>
                    </div>
                    <div class="ibox-body">
                        <table class="table table-striped table-hover" id="table_id">
                            <thead>
                            <tr>
                                <th>S.NO</th>
                                <th>category_id</th>
                                <th>sub_total</th>
                                <th>delivery_charge</th>
                                <th>Total_amount</th>
                                <th>status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if($order_data)
                                @foreach($order_data as $key => $value)
                                    <tr>
                                        <td>{{ $key+1 }}</td>
                                        <td>
                                            <a href="{{ route('all-product-list') }}" target="_blank"> {{ $value->cart_id }}</a>
                                        </td>
                                        <td>{{ $value->sub_total }}</td>
                                        <td>{{ $value->delivery_charge }}</td>
                                        <td>{{ $value->total_amount }}</td>
                                        <td>{{ ucfirst($value->status) }}</td>
                                        <td>
                                            <a href="{{ route('order.edit',$value->id) }}" class="btn btn-success" style="border-radius: 50%">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            {{--delelte data--}}
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>



    </div>

@endsection
@section('scripts')
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    {{--    <script rel="stylesheet" href="{{ asset('assets/admin/js/datatable.min.js') }}"></script>--}}
    <script>
        $(document).ready( function () {
            $('#table_id').DataTable();
        } );
    </script>
@endsection

resources/views/admin/pages.blade.php
@extends('admin.layouts.admin')
@section('content')
@section('styles')
    {{--        <link rel="stylesheet" href="{{ asset('assets/admin/css/datatable.min.css') }}">--}}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
@endsection
@section('content')
    <div class="page-content fade-in-up">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-head">
                        <div class="ibox-title">Pages List</div>
                    </div>
                    <div class="ibox-body">
                        <table class="table table-striped table-hover" id="table_id">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Thumbnail</th>
                                <th>Link</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(isset($page_list))
                                @foreach($page_list as $key => $value)
                                    <tr>
                                        <td>{{ $value->title }}</td>
                                        <td>
                                            @if($value->image != null && file_exists(public_path().'/uploads/pages/Thumb-'.$value->image))
                                                <img src="{{ asset('uploads/pages/Thumb-'.$value->image) }}" alt="img" style="max-width: 150px" class="img img-responsive img-thumbnail">
                                            @endif
                                        </td>
                                        <td>
                                            <a href="{{ route('pages.show',$value->slug) }}" target="_blank"> {{ route('pages.show',$value->slug) }}</a>
                                        </td>
                                        <td>
                                            <a href="{{ route('pages.edit',$value->id) }}" class="btn btn-success" style="border-radius: 50%">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>



    </div>

@endsection
@section('scripts')
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    {{--    <script rel="stylesheet" href="{{ asset('assets/admin/js/datatable.min.js') }}"></script>--}}
    <script>
        $(document).ready( function () {
            $('#table_id').DataTable();
        } );
    </script>
@endsection

resources/views/admin/product.blade.php
@extends('admin.layouts.admin')
@section('content')
@section('styles')
    {{--        <link rel="stylesheet" href="{{ asset('assets/admin/css/datatable.min.css') }}">--}}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
@endsection
@section('content')
    <div class="page-content fade-in-up">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-head">
                        <div class="ibox-title">Products List</div>
                        <div class="ibox-tools">
                            <a href="{{ route('products.create') }}"><button class="btn btn-success"><i class="fa fa-plus"></i> Add Category</button></a>
                        </div>
                    </div>
                    <div class="ibox-body">
                        <table class="table table-striped table-hover" id="table_id">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Parent_Category</th>
                                <th>Child_Category</th>
                                <th>Price(NPR.)</th>
                                <th>Discount(%)</th>
                                <th>Brand</th>
                                <th>Is Featured</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(isset($products_list))
                                @foreach($products_list as $key => $value)
                                    <tr>
                                        <td>
                                            <a href="{{  route('products.show',$value->slug) }}" target="_product_detail">
                                                {{$value->title }}
                                            </a>
                                        </td>
                                        <td>
                                            {{ $value->cat_info['title'] }}
                                        </td>
                                        <td>
                                            <Strong class="text-success">{{ $value->sub_cat_info['title'] }}</Strong>
                                        </td>
                                        <td>{{ number_format($value->price) }}</td>
                                        <td>{{ number_format($value->discount) }}%</td>
                                        <td>{{ $value->brand }}</td>
                                        <td>{{ $value->is_featured ? 'Yes' : 'No' }}</td>
                                        <td>{{ ucfirst($value->status) }}</td>
                                        <td>
                                            <a href="{{ route('products.edit',$value->id) }}" class="btn btn-success" style="border-radius: 50%">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            {{--delelte data--}}
                                            {{ Form::open(['url' => route('products.destroy',$value->id),'class' => 'form' ,'method' =>'delete','onsubmit' =>"return confirm('Are u sure u want to delete this products.?')"]) }}
                                            {{Form::button('<i class="fa fa-trash"></i>',['class' => 'btn btn-danger','style' => 'border-radius:50% ','type' => 'submit'])}}
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>



    </div>

@endsection
@section('scripts')
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    {{--    <script rel="stylesheet" href="{{ asset('assets/admin/js/datatable.min.js') }}"></script>--}}
    <script>
        $(document).ready( function () {
            $('#table_id').DataTable();
        } );
    </script>
@endsection

resources/views/admin/users.blade.php
@extends('admin.layouts.admin')
@section('content')
    @section('styles')
{{--        <link rel="stylesheet" href="{{ asset('assets/admin/css/datatable.min.css') }}">--}}
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    @endsection
    <div class="page-content fade-in-up">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox">
                    <div class="ibox-head">
                        <div class="ibox-title">Users List</div>
                        <div class="ibox-tools">
                            <a href="{{ route('users.create') }}"><button class="btn btn-success"><i class="fa fa-plus"></i> Add Users</button></a>
                        </div>
                    </div>
                    <div class="ibox-body">
                        <table class="table table-striped table-hover" id="table_id">
                            <thead>
                            <tr>
                                <th>name</th>
                                <th>email</th>
                                <th>role</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if($users_list)
                                @foreach($users_list as $key => $value)
                                    <tr>
                                        <td>{{ $value->name }}</td>
                                        <td>{{ $value->email }}</td>
                                        <td>{{ $value->role }}</td>
                                        <td>{{ ucfirst($value->status) }}</td>
                                        <td>
                                            <a href="{{ route('users.edit',$value->id) }}" class="btn btn-success" style="border-radius: 50%">
                                                <i class="fa fa-pencil"></i>
                                            </a>
                                            {{--delelte data--}}
                                            {{ Form::open(['url' => route('users.destroy',$value->id),'class' => 'form' ,'method' =>'delete','onsubmit' =>"return confirm('Are u sure u want to delete this users.?')"]) }}
                                            {{Form::button('<i class="fa fa-trash"></i>',['class' => 'btn btn-danger','style' => 'border-radius:50% ','type' => 'submit'])}}
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>



    </div>

@endsection
@section('scripts')
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
{{--    <script rel="stylesheet" href="{{ asset('assets/admin/js/datatable.min.js') }}"></script>--}}
        <script>
            $(document).ready( function () {
                $('#table_id').DataTable();
            } );
      </script>
@endsection